C
C******************************************************************************
C Actualiza los limites minimo y maximo para un buffer concreto
	SUBROUTINE UPDATELIMITS(NB)
	IMPLICIT NONE
	INTEGER NB
C
	INTEGER NBUFFMAX                 !numero de buffers de datos diferentes
	PARAMETER (NBUFFMAX=8)
        INCLUDE 'ndatamax.inc'
C
	INTEGER I
	INTEGER NDATABUFF(NBUFFMAX)
	REAL XMINBUFF(NBUFFMAX),XMAXBUFF(NBUFFMAX)
	REAL YMINBUFF(NBUFFMAX),YMAXBUFF(NBUFFMAX)
	REAL XDATA(NDATAMAX,NBUFFMAX),YDATA(NDATAMAX,NBUFFMAX)
	REAL EXDATA(NDATAMAX,NBUFFMAX),EYDATA(NDATAMAX,NBUFFMAX)
C
	COMMON/BLKNDATABUFF/NDATABUFF
	COMMON/BLKMINMAXBUFF/XMINBUFF,XMAXBUFF,YMINBUFF,YMAXBUFF
	COMMON/BLKXYDATA/XDATA,YDATA
	COMMON/BLKEXYDATA/EXDATA,EYDATA
C------------------------------------------------------------------------------
	XMINBUFF(NB)=XDATA(1,NB)-EXDATA(1,NB)
	XMAXBUFF(NB)=XDATA(1,NB)+EXDATA(1,NB)
	YMINBUFF(NB)=YDATA(1,NB)-EYDATA(1,NB)
	YMAXBUFF(NB)=YDATA(1,NB)+EYDATA(1,NB)
	IF(NDATABUFF(NB).GT.1)THEN
	  DO I=2,NDATABUFF(NB)
	    IF(XMINBUFF(NB).GT.XDATA(I,NB)-EXDATA(I,NB))
     +       XMINBUFF(NB)=XDATA(I,NB)-EXDATA(I,NB)
	    IF(XMAXBUFF(NB).LT.XDATA(I,NB)+EXDATA(I,NB))
     +       XMAXBUFF(NB)=XDATA(I,NB)+EXDATA(I,NB)
	    IF(YMINBUFF(NB).GT.YDATA(I,NB)-EYDATA(I,NB))
     +       YMINBUFF(NB)=YDATA(I,NB)-EYDATA(I,NB)
	    IF(YMAXBUFF(NB).LT.YDATA(I,NB)+EYDATA(I,NB))
     +       YMAXBUFF(NB)=YDATA(I,NB)+EYDATA(I,NB)
	  END DO
	END IF
C
	END
